# Ability Items cooldowns:
SlownessCooldown: 600 #30 seconds.
PrisonCooldown: 1200 #1 minute
IceAbilityCooldown: 1200 #1 minute

# Effect duration, example 600 === 30 seconds.
SlownessDuration: 600
PrisonDuration: 600
